site_name: Weka Wiki
theme: readthedocs
site_url: https://www.cs.waikato.ac.nz/ml/weka/wiki/
site_description: Some documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
pages:
    - Home: index.md
    - Resources:
      - FAQ: faq.md
      - Troubleshooting: troubleshooting.md
      - Learning resources: learning_resources.md
    - Packages: 
      - Overview: packages/index.md
      - Package manager: packages/manager.md
      - Unofficial packages: packages/unofficial.md
      - Package structure: packages/structure.md
    - Mailing list: mailing_list.md

